name: Build on Release created

on:
  release:
    types:
      - created
#on: push

jobs:
  build-macos:
    name: Build MacOS Packages (Intel)
    runs-on: macos-13

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 手动初始化和更新子模块
      - name: Fetch submodules
        run: |
          git submodule init
          git submodule update

      # 安装最新版本的Boost、CGAL和其他依赖
      - name: Install dependencies
        run: |
          brew install boost cgal mpfr eigen
          
          # 创建兼容层以处理任何剩余的兼容性问题
          mkdir -p /tmp/boost_compat/boost
          cat > /tmp/boost_compat/boost/next_prior.hpp << 'EOF'
          #ifndef BOOST_NEXT_PRIOR_HPP_INCLUDED
          #define BOOST_NEXT_PRIOR_HPP_INCLUDED
          
          #include <iterator>
          
          namespace boost {
              template <class T>
              inline T prior(T x) { return --x; }
          
              template <class T, class Distance>
              inline T prior(T x, Distance n) {
                  std::advance(x, -n);
                  return x;
              }
          
              template <class T>
              inline T next(T x) { return ++x; }
          
              template <class T, class Distance>
              inline T next(T x, Distance n) {
                  std::advance(x, n);
                  return x;
              }
          }
          
          #endif // BOOST_NEXT_PRIOR_HPP_INCLUDED
          EOF
          
          # 确保构建时包含兼容层
          echo "CPPFLAGS=-I/tmp/boost_compat" >> $GITHUB_ENV
          echo "BOOST_INCLUDEDIR=$(brew --prefix boost)/include" >> $GITHUB_ENV
          echo "BOOST_LIBRARYDIR=$(brew --prefix boost)/lib" >> $GITHUB_ENV
          echo "BOOST_VERSION=$(brew info --json boost | jq -r '.[0].versions.stable')" >> $GITHUB_ENV

      # 修复GMP下载链接
      - name: Fix GMP Download URL
        run: |
          sed -i.bak 's|https://gmplib.org/download/gmp/gmp-6.2.1.tar.bz2|https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.bz2|g' sh/cmake-deps.sh
          mkdir -p deps/download
          curl -L -o deps/download/gmp-6.2.1.tar.bz2 https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.bz2 || true

      # 构建项目
      - name: Build project
        run: |
          /bin/bash sh/cmake-deps.sh
          /bin/bash sh/cmake-build.sh

      # 测试
      - name: Test
        run: ./build/LunarMP version && ./build/LunarMP ptest
      
      # 准备输出
      - name: Prepare output
        run: mkdir output && cp ./build/LunarMP ./output/LunarMP

      # 代码签名
      - name: Code signing
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Sign binary
        run: codesign -s ${{ secrets.CERTIFICATES_NAME }} ./output/LunarMP

      # 打包
      - name: Zip output
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          filename: LunarMP-mac.zip
          directory: ./
          path: ./output

      # 上传
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: LunarMP-mac.zip

  build-macos-arm64:
    name: Build MacOS Packages (ARM64)
    runs-on: macos-13

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      # 手动初始化和更新子模块
      - name: Fetch submodules
        run: |
          git submodule init
          git submodule update

      # 安装最新版本的Boost、CGAL和其他依赖
      - name: Install dependencies
        run: |
          brew install boost cgal mpfr eigen
          
          # 创建兼容层以处理任何剩余的兼容性问题
          mkdir -p /tmp/boost_compat/boost
          cat > /tmp/boost_compat/boost/next_prior.hpp << 'EOF'
          #ifndef BOOST_NEXT_PRIOR_HPP_INCLUDED
          #define BOOST_NEXT_PRIOR_HPP_INCLUDED
          
          #include <iterator>
          
          namespace boost {
              template <class T>
              inline T prior(T x) { return --x; }
          
              template <class T, class Distance>
              inline T prior(T x, Distance n) {
                  std::advance(x, -n);
                  return x;
              }
          
              template <class T>
              inline T next(T x) { return ++x; }
          
              template <class T, class Distance>
              inline T next(T x, Distance n) {
                  std::advance(x, n);
                  return x;
              }
          }
          
          #endif // BOOST_NEXT_PRIOR_HPP_INCLUDED
          EOF
          
          # 确保构建时包含兼容层
          echo "CPPFLAGS=-I/tmp/boost_compat" >> $GITHUB_ENV
          echo "BOOST_INCLUDEDIR=$(brew --prefix boost)/include" >> $GITHUB_ENV
          echo "BOOST_LIBRARYDIR=$(brew --prefix boost)/lib" >> $GITHUB_ENV
          echo "BOOST_VERSION=$(brew info --json boost | jq -r '.[0].versions.stable')" >> $GITHUB_ENV
          
          # 设置ARM64架构
          echo "CMAKE_OSX_ARCHITECTURES=arm64" >> $GITHUB_ENV

      # 修复GMP下载链接
      - name: Fix GMP Download URL
        run: |
          sed -i.bak 's|https://gmplib.org/download/gmp/gmp-6.2.1.tar.bz2|https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.bz2|g' sh/cmake-deps.sh
          mkdir -p deps/download
          curl -L -o deps/download/gmp-6.2.1.tar.bz2 https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.bz2 || true

      # 构建项目
      - name: Build project
        run: |
          /bin/bash sh/cmake-deps.sh
          /bin/bash sh/cmake-build.sh

      # 测试
      - name: Test
        run: ./build/LunarMP version && ./build/LunarMP ptest
      
      # 准备输出
      - name: Prepare output
        run: mkdir output && cp ./build/LunarMP ./output/LunarMP

      # 代码签名
      - name: Code signing
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Sign binary
        run: codesign -s ${{ secrets.CERTIFICATES_NAME }} ./output/LunarMP

      # 打包
      - name: Zip output
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          filename: LunarMP-mac-arm64.zip
          directory: ./
          path: ./output

      # 上传
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: LunarMP-mac-arm64.zip

  build-windows:
    name: Build Windows packages
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      # 手动初始化和更新子模块
      - name: Fetch submodules
        run: |
          git submodule init
          git submodule update

      # 安装特定版本的Boost
      - name: Install compatible Boost version
        run: |
          choco install boost-msvc-14.2 --version=1.71.0 --allow-downgrade

      # 修复GMP下载链接
      - name: Fix GMP Download URL
        shell: bash
        run: |
          sed -i 's|https://gmplib.org/download/gmp/gmp-6.2.1.tar.bz2|https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.bz2|g' sh/cmake-deps.sh
          mkdir -p deps/download
          curl -L -o deps/download/gmp-6.2.1.tar.bz2 https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.bz2 || true

      # 设置MSYS2
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: inherit
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            m4
            gmp
            mpfr
            mingw-w64-x86_64-eigen3
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-cgal

      # 修复MSYS2签名问题
      - name: Fix MSYS2 Signatures
        shell: msys2 {0}
        run: |
          echo "SigLevel = Never" >> /etc/pacman.conf
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed m4 gmp mpfr mingw-w64-x86_64-eigen3 mingw-w64-x86_64-boost mingw-w64-x86_64-cgal

      # 构建项目
      - name: Build project
        shell: msys2 {0}
        run: |
          sh sh/cmake-deps.sh
          sh sh/cmake-build.sh

      # 测试
      - name: Test
        run: ./build/LunarMP.exe version && ./build/LunarMP.exe ptest
      
      # 准备输出
      - name: Prepare output
        run: mkdir output && cp ./build/LunarMP.exe ./output/LunarMP.exe

      # 打包
      - name: Zip output
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          filename: LunarMP-win64.zip
          directory: ./
          path: ./output

      # 上传
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./LunarMP-win64.zip

  build-ubuntu:
    name: Build Ubuntu packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      # 手动初始化和更新子模块
      - name: Fetch submodules
        run: |
          git submodule init
          git submodule update

      # 安装依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev
          sudo apt-get install -y libmpfr-dev
          sudo apt-get install -y libboost-all-dev
          sudo apt-get install -y libeigen3-dev
          # 安装最新版本的CGAL
          sudo apt-get install -y libcgal-dev

      # 修复GMP下载链接
      - name: Fix GMP Download URL
        run: |
          sed -i 's|https://gmplib.org/download/gmp/gmp-6.2.1.tar.bz2|https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.bz2|g' sh/cmake-deps.sh
          mkdir -p deps/download
          curl -L -o deps/download/gmp-6.2.1.tar.bz2 https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.bz2 || true
          
      # 构建项目
      - name: Build project
        run: |
          /bin/bash sh/cmake-deps.sh
          /bin/bash sh/cmake-build.sh

      # 测试
      - name: Test
        run: ./build/LunarMP version && ./build/LunarMP ptest
      
      # 准备输出
      - name: Prepare output
        run: mkdir output && cp ./build/LunarMP ./output/LunarMP

      # 打包
      - name: Zip output
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          filename: LunarMP-linux.zip
          directory: ./
          path: ./output

      # 上传
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: LunarMP-linux.zip
